
Linux:
  cc: gcc
  acc: nvc
  flags:
    cc: -g -O2 -std=c99 -x c -D_POSIX_C_SOURCE=2
    ld: -lm
    acc: -lm -fast -Minfo=accel -acc=gpu -gpu=mem:managed -DOPENACC -x c -D_POSIX_C_SOURCE=2
    nexus: -DUSE_NEXUS -lNeXus
    mpi: -DUSE_MPI -lmpi
    gsl: -lgsl -lgslcblas
    xrl: -lxrl
  mpi:
    cc: mpicc
    run: mpirun
    nodes: auto
  ext: .out
Darwin:
  cc: /usr/bin/clang
  acc: /usr/bin/clang
  flags:
    cc: -g -O2 -std=c99 -x c -D_DARWIN_C_SOURCE
    ld: -lm
    acc: -lm -ta:multicore -DOPENACC -x c -D_DARWIN_C_SOURCE
    nexus: -DUSE_NEXUS -lNeXus
    mpi:  -DUSE_MPI -lmpi
    gsl: -lgsl -lgslcblas
    xrl: -lxrl
  mpi:
    cc: mpicc.clang
    run: mpirun
    nodes: auto
  ext: .out
Windows:
  cc: cl.exe
  acc: there_is_no_acc_compiler_for_windows.exe
  flags:
    cc: /DWIN32 /D_WINDOWS /Zi /O2 /Ob1 /DNDEBUG /DPATH_MAX=4096
    ld: /link
    acc: /O2
    nexus: /DUSE_NEXUS NeXus.lib
    mpi: /DUSE_MPI /link msmpi.lib
    gsl: /link gsl.lib gslcblas.lib
    xrl: /lib xrl.lib
  mpi:
    cc: mpicc.bat
    run: mpiexec.exe
    nodes: auto
  ext: .exe