/*
 * This file was auto-generated by speedy-antlr-tool v1.4.3
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#define PY_SSIZE_T_CLEAN
#include <Python.h>

#include <cstring>
#include <any>

#include "antlr4-runtime.h"
#include "McCompLexer.h"
#include "McCompParser.h"
#include "speedy_antlr.h"

#include "sa_mccomp_translator.h"
antlr4::tree::ParseTree* get_parse_tree_prog(McCompParser *parser) {return parser->prog();}
antlr4::tree::ParseTree* get_parse_tree_component_definition(McCompParser *parser) {return parser->component_definition();}
antlr4::tree::ParseTree* get_parse_tree_component_trace(McCompParser *parser) {return parser->component_trace();}
antlr4::tree::ParseTree* get_parse_tree_component_parameter_set(McCompParser *parser) {return parser->component_parameter_set();}
antlr4::tree::ParseTree* get_parse_tree_component_define_parameters(McCompParser *parser) {return parser->component_define_parameters();}
antlr4::tree::ParseTree* get_parse_tree_component_set_parameters(McCompParser *parser) {return parser->component_set_parameters();}
antlr4::tree::ParseTree* get_parse_tree_component_out_parameters(McCompParser *parser) {return parser->component_out_parameters();}
antlr4::tree::ParseTree* get_parse_tree_component_parameters(McCompParser *parser) {return parser->component_parameters();}
antlr4::tree::ParseTree* get_parse_tree_component_parameter(McCompParser *parser) {return parser->component_parameter();}
antlr4::tree::ParseTree* get_parse_tree_share(McCompParser *parser) {return parser->share();}
antlr4::tree::ParseTree* get_parse_tree_display(McCompParser *parser) {return parser->display();}
antlr4::tree::ParseTree* get_parse_tree_component_ref(McCompParser *parser) {return parser->component_ref();}
antlr4::tree::ParseTree* get_parse_tree_coords(McCompParser *parser) {return parser->coords();}
antlr4::tree::ParseTree* get_parse_tree_reference(McCompParser *parser) {return parser->reference();}
antlr4::tree::ParseTree* get_parse_tree_dependency(McCompParser *parser) {return parser->dependency();}
antlr4::tree::ParseTree* get_parse_tree_declare(McCompParser *parser) {return parser->declare();}
antlr4::tree::ParseTree* get_parse_tree_uservars(McCompParser *parser) {return parser->uservars();}
antlr4::tree::ParseTree* get_parse_tree_initialise(McCompParser *parser) {return parser->initialise();}
antlr4::tree::ParseTree* get_parse_tree_save(McCompParser *parser) {return parser->save();}
antlr4::tree::ParseTree* get_parse_tree_finally_(McCompParser *parser) {return parser->finally_();}
antlr4::tree::ParseTree* get_parse_tree_metadata(McCompParser *parser) {return parser->metadata();}
antlr4::tree::ParseTree* get_parse_tree_category(McCompParser *parser) {return parser->category();}
antlr4::tree::ParseTree* get_parse_tree_initializerlist(McCompParser *parser) {return parser->initializerlist();}
antlr4::tree::ParseTree* get_parse_tree_assignment(McCompParser *parser) {return parser->assignment();}
antlr4::tree::ParseTree* get_parse_tree_expr(McCompParser *parser) {return parser->expr();}
antlr4::tree::ParseTree* get_parse_tree_shell(McCompParser *parser) {return parser->shell();}
antlr4::tree::ParseTree* get_parse_tree_search(McCompParser *parser) {return parser->search();}
antlr4::tree::ParseTree* get_parse_tree_unparsed_block(McCompParser *parser) {return parser->unparsed_block();}

antlr4::tree::ParseTree* get_parse_tree(McCompParser *parser, const char *entry_rule_name) {
    static std::map<std::string, antlr4::tree::ParseTree* (*)(McCompParser*)> table
    {
        {"prog", &get_parse_tree_prog},
        {"component_definition", &get_parse_tree_component_definition},
        {"component_trace", &get_parse_tree_component_trace},
        {"component_parameter_set", &get_parse_tree_component_parameter_set},
        {"component_define_parameters", &get_parse_tree_component_define_parameters},
        {"component_set_parameters", &get_parse_tree_component_set_parameters},
        {"component_out_parameters", &get_parse_tree_component_out_parameters},
        {"component_parameters", &get_parse_tree_component_parameters},
        {"component_parameter", &get_parse_tree_component_parameter},
        {"share", &get_parse_tree_share},
        {"display", &get_parse_tree_display},
        {"component_ref", &get_parse_tree_component_ref},
        {"coords", &get_parse_tree_coords},
        {"reference", &get_parse_tree_reference},
        {"dependency", &get_parse_tree_dependency},
        {"declare", &get_parse_tree_declare},
        {"uservars", &get_parse_tree_uservars},
        {"initialise", &get_parse_tree_initialise},
        {"save", &get_parse_tree_save},
        {"finally_", &get_parse_tree_finally_},
        {"metadata", &get_parse_tree_metadata},
        {"category", &get_parse_tree_category},
        {"initializerlist", &get_parse_tree_initializerlist},
        {"assignment", &get_parse_tree_assignment},
        {"expr", &get_parse_tree_expr},
        {"shell", &get_parse_tree_shell},
        {"search", &get_parse_tree_search},
        {"unparsed_block", &get_parse_tree_unparsed_block}
    };

    auto entry = table.find(entry_rule_name);
    if (entry != table.end()) {
        return (*(entry->second))(parser);
    } else {
        PyErr_SetString(PyExc_ValueError, "Invalid entry_rule_name");
        throw speedy_antlr::PythonException();
    }
}

/*
 * Python function prototype:
 *  do_parse(
 *      parser_cls:antlr4.Parser,
 *      stream:antlr4.InputStream,
 *      entry_rule_name:str,
 *      sa_err_listener:SA_ErrorListener
 *  )
 */
PyObject* do_parse(PyObject *self, PyObject *args) {
    PyObject *strdata = NULL;
    PyObject *result = NULL;
    PyObject *token_module = NULL;

    try {
        // Get args
        PyObject *parser_cls = NULL;
        PyObject *stream = NULL;
        const char *entry_rule_name = NULL;
        PyObject *sa_err_listener = NULL;
        if(!PyArg_ParseTuple(args,
            "OOsO:do_parse",
            &parser_cls, &stream, &entry_rule_name, &sa_err_listener
        )) {
            return NULL;
        }

        // Extract input stream's string
        const char *cstrdata;
        Py_ssize_t bufsize;
        strdata = PyObject_GetAttrString(stream, "strdata");
        if(!strdata) throw speedy_antlr::PythonException();
        cstrdata = PyUnicode_AsUTF8AndSize(strdata, &bufsize);
        if(!cstrdata) throw speedy_antlr::PythonException();

        // Create an antlr InputStream object
        antlr4::ANTLRInputStream cpp_stream(cstrdata, bufsize);

        // in case error listener is overridden
        token_module = PyImport_ImportModule("antlr4.Token");
        if(!token_module) throw speedy_antlr::PythonException();
        speedy_antlr::Translator translator(parser_cls, stream);
        speedy_antlr::ErrorTranslatorListener err_listener(&translator, sa_err_listener);

        // Lex
        McCompLexer lexer(&cpp_stream);
        if(sa_err_listener != Py_None){
            lexer.removeErrorListeners();
            lexer.addErrorListener(&err_listener);
        }
        antlr4::CommonTokenStream token_stream(&lexer);
        token_stream.fill();

        // Parse
        McCompParser parser(&token_stream);
        if(sa_err_listener != Py_None){
            parser.removeErrorListeners();
            parser.addErrorListener(&err_listener);
        }
        antlr4::tree::ParseTree *parse_tree;
        parse_tree = get_parse_tree(&parser, entry_rule_name);

        // Translate Parse tree to Python
        SA_McCompTranslator visitor(&translator);
        result = std::any_cast<PyObject *>(visitor.visit(parse_tree));

        // Clean up data
        Py_XDECREF(token_module);
        Py_XDECREF(strdata);

        return result;

    } catch(speedy_antlr::PythonException &e) {
        Py_XDECREF(token_module);
        Py_XDECREF(strdata);
        Py_XDECREF(result);

        // Python exception already has error indicator set
        return NULL;
    } catch(...) {
        Py_XDECREF(token_module);
        Py_XDECREF(strdata);
        Py_XDECREF(result);

        // An internal C++ exception was thrown.
        // Set error indicator to a generic runtime error
        PyErr_SetString(PyExc_RuntimeError, "Internal error");
        return NULL;
    }
}


extern "C" {

    static PyObject* c_do_parse(PyObject *self, PyObject *args) {
        return do_parse(self, args);
    }

    static PyMethodDef methods[] = {
        {
            "do_parse",  c_do_parse, METH_VARARGS,
            "Run parser"
        },
        {NULL, NULL, 0, NULL} /* Sentinel */
    };

    static struct PyModuleDef module = {
        PyModuleDef_HEAD_INIT,
        "sa_mccomp_cpp_parser",   /* name of module */
        NULL, /* module documentation, may be NULL */
        -1,       /* size of per-interpreter state of the module,
                    or -1 if the module keeps state in global variables. */
        methods
    };
}


PyMODINIT_FUNC
PyInit_sa_mccomp_cpp_parser(void) {
    PyObject *m = PyModule_Create(&module);
    return m;
}