name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main
  release:
    types:
      - published

jobs:
  build_sdist_and_wheel:
    name: Build SDist and Wheel
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Build SDist
      run: pipx run build

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*

  upload_all:
    name: Upload if release
    needs: [build_sdist_and_wheel]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mccode_antlr
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v4

    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1
